# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('EDC', 'Education'), ('CSH', 'Cosha'), ('HST', 'Hostel'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
    ]
